card1 = Card.create(name: "shapes", filename: "card1.png")
card2 = Card.create(name: "planet", filename: "card2.jpg")
card3 = Card.create(name: "smiley", filename: "card3.jpg")
card4 = Card.create(name: "the switch", filename: "card4.jpg")
card5 = Card.create(name: "telekensis", filename: "card5.jpg")
card6 = Card.create(name: "hypnotic", filename: "card6.jpg")
card7 = Card.create(name: "bucktooth", filename: "card7.jpg")
card8 = Card.create(name: "thought balloon", filename: "card8.jpg")
card9 = Card.create(filename: "card9.jpg")
card10 = Card.create(filename: "card10.jpg")
card11 = Card.create(filename: "card11.jpg")
card12 = Card.create(filename: "card12.jpg")
card13 = Card.create(filename: "card13.jpg")
card14 = Card.create(filename: "card14.jpg")
card15 = Card.create(filename: "card15.png")
card16 = Card.create(filename: "card16.png")
card17 = Card.create(filename: "card17.png")
card18 = Card.create(filename: "card18.png")
card19 = Card.create(filename: "card19.png")
card20 = Card.create(filename: "card20.png")
card21 = Card.create(filename: "card21.png")
card22 = Card.create(filename: "card22.png")
card23 = Card.create(filename: "card23.png")
card24 = Card.create(filename: "card24.png")
card25 = Card.create(filename: "card25.png")
card26 = Card.create(filename: "card26.png")
card27 = Card.create(filename: "card27.png")
card28 = Card.create(filename: "card28.png")
card29 = Card.create(filename: "card29.png")
card30 = Card.create(filename: "card30.png")
card31 = Card.create(filename: "card31.png")
card32 = Card.create(filename: "card32.png")

rule1 = Rule.create(winner: card1, loser: card2, rule: "Planets are made of shapes" )
rule2 = Rule.create(winner: card3, loser: card1, rule: "Nothing beats a smile" )
rule3 = Rule.create(winner: card4, loser: card1, rule: "Power off the shapes" )
rule4 = Rule.create(winner: card5, loser: card1, rule: "moving shapes with your mind" )
rule5 = Rule.create(winner: card1, loser: card6, rule: "shapes can not be hypnotized" )
rule6 = Rule.create(winner: card7, loser: card1, rule: "that tooth is too charming" )
rule7 = Rule.create(winner: card8, loser: card1, rule: "You can dream of winning" )

rule13 = Rule.create(winner: card2, loser: card3, rule: "Smiling won't stop a planet" )
rule8 = Rule.create(winner: card2, loser: card4, rule: "A planet can't be turned off" )
rule9 = Rule.create(winner: card5, loser: card2, rule: "The planet will stop if you think about it" )
rule10 = Rule.create(winner: card6, loser: card2, rule: "Hypnotized the entire planet" )
rule11 = Rule.create(winner: card7, loser: card2, rule: "That tooth is too charming" )
rule12 = Rule.create(winner: card8, loser: card2, rule: "You can dream of winning" )

rule14 = Rule.create(winner: card3, loser: card4, rule: "You can light up the room with a smile" )
rule15 = Rule.create(winner: card5, loser: card3, rule: "Force your smile upside down" )
rule16 = Rule.create(winner: card6, loser: card3, rule: "hypnotized that big eye" )
rule17 = Rule.create(winner: card7, loser: card3, rule: "smile vs smile, but that bucktooth is too charming." )
rule18 = Rule.create(winner: card8, loser: card3, rule: "You can dream of winning" )

rule19 = Rule.create(winner: card5, loser: card4, rule: "flip that switch with your mind" )
rule20 = Rule.create(winner: card6, loser: card5, rule: "telekensis vs hypnosis, hynosis wins" )
rule21 = Rule.create(winner: card5, loser: card7, rule: "pull that tooth" )
rule22 = Rule.create(winner: card8, loser: card4, rule: "You can dream of winning" )

rule23 = Rule.create(winner: card6, loser: card4, rule: "you don't want to flip that switch" )
rule24 = Rule.create(winner: card7, loser: card4, rule: "that tooth is too charming" )
rule25 = Rule.create(winner: card8, loser: card5, rule: "You can dream of winning" )

rule26 = Rule.create(winner: card7, loser: card6, rule: "that tooth is too charming" )
rule27 = Rule.create(winner: card8, loser: card6, rule: "You can dream of winning" )

rule28 = Rule.create(winner: card7, loser: card8, rule: "You can't dream of winning here" )